default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool:     <%= ENV["DATABASE_POOL"] || '5' %>
  host:     <%= ENV["DATABASE_HOST"] || '127.0.0.1' %>
  username: <%= ENV["DATABASE_USER"] || 'root' %>
  database: <%= ENV["DATABASE_NAME"] || 'dash' %>
  password: <%= ENV["DATABASE_PASSWORD"] || '' %>

development:
  <<: *default
  database: dash_development

test:
  <<: *default
  database: dash_test

production:
  <<: *default

staging:
  <<: *default
